package com.kalo.document.enums;

public enum DocumentType {

    BUSINESS_REGISTRATION,
    TAXI_LICENSE,

    DRIVING_LICENSE,
    PROFESSIONAL_CERTIFICATE,

    VEHICLE_REGISTRATION,
    INSURANCE,
    PASSENGER_INSURANCE,
    TECHNICAL_INSPECTION,
    TAXIMETER_VERIFICATION
}